name: Our Amazing Workflow! Team 3 is the best

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --verbosity normal
      
    - name: List out directory contents
      run: |
          echo "Listing the contents of the GitHub workspace directory"
          ls ${{ github.workspace }}

          echo "Recursively listing all contents of the current directory"
          ls -R
          
    - name: Publish portal project in Release mode
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/
      
    - name: Upload a Build Artifact for Web Portal
      uses: actions/upload-artifact@v2.1.3
      with:
        name: portal
        path: ${{ github.workspace }}/taa-portal/
        if-no-files-found: error
        
    - name: Upload bicep
      uses: actions/upload-artifact@v2.1.3
      with:
        name: bicep
        path: ${{ github.workspace }}/deploy.bicep/
        if-no-files-found: error
        
        
        
#   deploy:

#     runs-on: windows-latest
#     needs: build
#     environment : 
#       name : "production"
#       url : ${{ steps.deploy-to-webapp.output.webapp-url }}
      
#     steps:
#       - name: Download Artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#          name: portal
       
#       - name: 'Run Azure webapp deploy action using publish profile credentials'
#         uses: azure/webapps-deploy@v2
#         id : deploy-to-webapp
#         with:
#          app-name: "AnimalAdoptionDev-2"
#          publish-profile: ${{ secrets.DEVPUBLISHSETTINGS2 }}
#          package : .
         
  application_settings:

    runs-on: windows-latest
#     needs: deploy       
    
    steps:
      - name: login with SP
        uses: Azure/login@v1.1
        with:
          creds: ${{secrets.DEV_SERVICE_PRINCIPAL_AZURE}}
      - name : get from keyvault
        uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "animalkeyvault"
          secrets: 'Globalpassword'
        id: myGetSecretAction

      - name: Set Web App ACR authentication  
        uses: azure/appservice-settings@v1    
        with:   
          app-name: 'AnimalAdoptionDev-2'    
          app-settings-json: |
           [
           {
            "name": "GlobalPassword",
            "value": "${{ steps.myGetSecretAction.outputs.Globalpassword }}",
            "slotSetting": false
           }
           ]

  bicep_provisioning:

    runs-on: windows-latest
    
    steps:
        - name: login with SP
          uses: Azure/login@v1.1
          with:
           creds: ${{secrets.PROD_PUBLISHED_SETTINGS}}
         
        - name: Download bicep
          uses: actions/download-artifact@v2
          with:
           name: bicep
           path: ./bicep-template/
           
        - name: deploy from bicep
          uses: azure/arm-deploy@v1
          with:
           resourceGroupName: DevOpsGitHub-2022-09-22-team-03-prod
           template: ./bicep-template/deploy.bicep
           parameters: tenantGuid=ab5eb3d0-6067-40ee-b4c0-a2ce05dbf039 appServicePlanName=ProdAnimalAdoption keyVaultName=prodanimalkeyvault webAppName=prodwebanimaladoption resourceGroupServicePrincipalManagedApplicationObjectId=82eec69e-37a8-4e11-a274-dffd0985dc2d
           deploymentMode: incremental         

  deployprod:
    needs: [build, bicep_provisioning]

    runs-on: windows-latest
    environment: 
      name : "production"
      url : ${{ steps.deploy-to-webapp.output.webapp-url }}
      
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
         name: portal
       
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        id : deploy-to-webapp
        with:
         app-name: "prodwebanimaladoption"
         publish-profile: ${{ secrets.prod_published_settings2 }}
         package : .
           
