name: Our Amazing Workflow! Team 3 is the best

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Setup .NET 
#       uses: actions/setup-dotnet@v2
#       with:
#         dotnet-version: 3.1.x
        
#     - name: Restore dependencies
#       run: dotnet restore
      
#     - name: Build
#       run: dotnet build --configuration Release --no-restore
      
#     - name: Test
#       run: dotnet test --verbosity normal
      
#     - name: List out directory contents
#       run: |
#           echo "Listing the contents of the GitHub workspace directory"
#           ls ${{ github.workspace }}

#           echo "Recursively listing all contents of the current directory"
#           ls -R
          
#     - name: Publish portal project in Release mode
#       run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/
      
#     - name: Upload a Build Artifact for Web Portal
#       uses: actions/upload-artifact@v2.1.3
#       with:
#         name: portal
#         path: ${{ github.workspace }}/taa-portal/
#         if-no-files-found: error
        
#   deploy:

#     runs-on: windows-latest
#     needs: build
#     environment : 
#       name : "production"
#       url : ${{ steps.deploy-to-webapp.output.webapp-url }}
      
#     steps:
#       - name: Download Artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#          name: portal
       
#       - name: 'Run Azure webapp deploy action using publish profile credentials'
#         uses: azure/webapps-deploy@v2
#         id : deploy-to-webapp
#         with:
#          app-name: "AnimalAdoptionDev-2"
#          publish-profile: ${{ secrets.DEVPUBLISHSETTINGS2 }}
#          package : .
         
  application_settings:

    runs-on: windows-latest
#     needs: deploy       
    
    steps:
      - name: login with SP
        uses: Azure/login@v1.1
        with:
          creds: ${{secrets.DEV_SERVICE_PRINCIPAL_AZURE}}
          
#       - uses: azure/appservice-settings@v1
#         with:
#          app-name: 'AnimalAdoptionDev-2'
#          app-settings-json: '${{ secrets.DEVPUBLISHSETTINGS2 }}' 


      - name: Set Web App ACR authentication  
        uses: azure/appservice-settings@v1    
        with:   
          app-name: 'AnimalAdoptionDev-2'    
          app-settings-json: |
           [
           {
            "name": "GlobalPassword",
            "value": "${{ secrets.DEV_GLOBALPASSWORD }}",
            "slotSetting": false
           }
           ]

